name: Build

on:
  push:
    branches:
    - master
    - release/*

jobs:
  test:
    name: Testing on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Run tests with Ward
      uses: abatilo/actions-poetry@v1.5.0
      with:
        poetry_version: 1.0.3
        python_version: ${{ matrix.python-version }}
        args: run ward

# TODO: Update to use the Makefile and actually enforce this.
#    - name: Lint with flake8 (CONFIG OUTDATED)
#      run: |
#        # stop the build if there are Python syntax errors or undefined names
#        python3.7 -m poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        python3.7 -m poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
