name: Ward release to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Build Python distributon
      run: sudo python "$GITHUB_WORKSPACE/setup.py" sdist bdist_wheel
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@66f4ba74
      with:
        user: __token__
        password: ${{ secrets.pypi_api_token }}
