name: Ward release to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and publish to PyPI with Poetry
      uses: abatilo/actions-poetry@v1.5.0
      with:
        poetry_version: 1.0.3
        python_version: 3.8
        args: publish --build
      working-directory: ${{ github.workspace }}
