name: Ward release to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Python distribution
      run: |
        python3 -m pip install --user --upgrade setuptools wheel
        python3 "$GITHUB_WORKSPACE/setup.py" sdist bdist_wheel
    - name: Publish a Python distribution to PyPI
      if: success()
      uses: pypa/gh-action-pypi-publish@66f4ba74
      with:
        user: __token__
        password: ${{ secrets.pypi_api_token }}
