name: Ward release to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: "Install Poetry"
      run: |
        python3.7 -m pip install --user --upgrade poetry
    - name: "Build & publish to PyPI using Poetry"
      run: |
        python3.7 -m poetry build
        python3.7 -m poetry publish -u __token__ -p ${{ secrets.pypi_api_token }}
      working-directory: ${{ github.workspace }}
