name: Ward release to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and publish Python distribution to PyPI
      run: |
        python3 -m pip install --user --upgrade flit
        python3 -m flit publish
      working-directory: ${{ github.workspace }}
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.pypi_api_token }}
